index:
    path: /
    controller: App\Controller\DefaultController::index

static_route:
    path: /information/{page}
    controller: App\Controller\DefaultController:staticPage
    requirements:
        page: cgv|mentions-legales|qui-sommes-nous

contact:
    path: /contact
    controller: App\Controller\ContactController:contact

livres:
    path: /livres
    controller: App\Controller\CatalogueController:livres