index:
    path: /
    controller: App\Controller\DefaultController::index

static_route:
    path: /information/{page}
    controller: App\Controller\DefaultController::staticPage
    requirements:
        page: cgv|mentions-legales|qui-sommes-nous

contact:
    path: /contact
    controller: App\Controller\ContactController::contact

gigastore_fiche_livre:
    path: /fiche-livre/{id}
    controller: App\Controller\CatalogueController::ficheLivre

gigastore_livres:
    path: /liste-livres/{critere}
    controller: App\Controller\CatalogueController::index
    defaults:
        critere: TOUT

gigastore_revendeurs:
    path: /liste-revendeurs
    controller: App\Controller\RevendeurController::index

gigastore_admin_add_entity:
    path: /admin/add/{entity}
    controller: App\Controller\GenreAdminController::addEntity

gigastore_admin_edit_entity:
    path: /admin/edit/{entity}/{id}
    controller: App\Controller\GenreAdminController::editEntity

gigastore_admin_delete_entity:
    path: /admin/delete/{entity}/{id}
    controller: App\Controller\GenreAdminController::deleteEntity

gigastore_admin_list_entity:
    path: /admin/{entity}
    controller: App\Controller\GenreAdminController::DisplayEntity

gigastore_liste_themes:
    path: /liste-themes
    controller: App\Controller\ThemeController::afficherTheme

gigastore_choisir_themes:
    path: /liste-themes/{theme}
    controller: App\Controller\ThemeController::choisirTheme